name: Check All

on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Build Docker
        working-directory: hellen-one
        run: |
          bash step1-build-docker.sh

      - name: Copy Files
        working-directory: .
        run: |
          docker run --rm -it --entrypoint python3 -v "$(pwd)":/${PWD##*/} hellen-one ./bin/copy_from_Kicad.py "frames:alphax_" "/${PWD##*/}" "../../gerber" "2ch" "c"

      - name: Create Board
        working-directory: .
        run: |
          docker run --rm -it --entrypoint bash -v "$(pwd)":/${PWD##*/} hellen-one ./bin/create_board_with_prefix.sh "alphax_" "/${PWD##*/}" "2ch" "c" "bom_replace_alphax-2ch-c.csv " "0,4"
