name: Check All

on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Build Docker
        run: |
          bash hellen-one/step1-build-docker.sh
